---
name: gateway

services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=linuxserver-test.com
      - SUBDOMAINS=www,ombi
      # - EXTRA_DOMAINS=
      - VALIDATION=http
      - STAGING=true
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network